import React, { useEffect, useState } from 'react';
import { usePolling } from '../../hooks/usePolling';
import { hasib, dashboard } from '../../lib/dashboard/api';
import { formatDateTime } from '../../lib/dashboard/format';
import { Money } from './Badges';
import { photoProblem, uploadProductPhoto, PHOTO_TYPES } from '../../lib/hasib/photo.js';
import { buildRealEstateSubmission } from '../../lib/hasib/realEstateForms.js';
import { ActionCards, EmptyState, HorizontalBars, MetricCards, PageHeader } from './DashboardVisuals';
import { Icon } from '../ui/Icon';

const empty = { items: [] };
const ACTIONS_BY_MODE = { today: [], properties: ['property'], deals: ['opportunity', 'viewing', 'offer', 'follow-up', 'close'], money: [], team: ['invite'] };
const actionForm = (mode, action) => (ACTIONS_BY_MODE[mode] || []).includes(action) ? (action === 'follow-up' ? 'draft' : action) : '';

export function RealEstateDashboard({ mode, s, h, overview, timezone = 'Asia/Muscat', onChanged, onGo, initialAction = '' }) {
  const tr = (en, ar) => s.ar ? ar : en;
  const [form, setForm] = useState(actionForm(mode, initialAction)), [values, setValues] = useState({}), [busy, setBusy] = useState(false), [error, setError] = useState(''), [propertyPhotos, setPropertyPhotos] = useState([]);
  const manager = overview.workspaceRole === 'manager';
  useEffect(() => {
    const next = actionForm(mode, initialAction);
    setForm(next); setValues({}); setPropertyPhotos([]); setError('');
  }, [mode, initialAction]);
  const state = usePolling(async () => {
    if (mode === 'today') return { summary: await hasib('real_estate_overview'), tasks: await hasib('real_estate_tasks') };
    if (mode === 'properties') return { properties: await hasib('properties'), team: manager ? await hasib('team_list') : empty };
    if (mode === 'money') return { commissions: await hasib('commissions'), insights: await hasib('real_estate_insights') };
    if (mode === 'team') return { team: await hasib('team_list') };
    const [opportunities, viewings, offers, drafts, contacts, properties, team, summary] = await Promise.all([
      hasib('opportunities'), hasib('viewings'), hasib('offers'), hasib('drafts'), dashboard('contacts', { limit: 50 }), hasib('properties'), manager ? hasib('team_list') : Promise.resolve(empty), hasib('real_estate_overview'),
    ]);
    return { opportunities, viewings, offers, drafts, contacts, properties, team, summary };
  }, [mode], { interval: 30000 });
  const data = state.data || {};
  const run = async (operation, body = {}) => {
    if (busy) return;
    setBusy(true); setError('');
    try { const result = await hasib(operation, body); if (result.invitationDelivery === 'failed') setError(tr('Invitation saved, but email delivery failed. Use resend to try again.', 'تم حفظ الدعوة، لكن تعذر إرسال البريد. استخدم إعادة الإرسال للمحاولة مجددًا.')); for (const photo of propertyPhotos) URL.revokeObjectURL(photo.preview); setPropertyPhotos([]); setForm(''); setValues({}); await state.refresh(); onChanged?.(); }
    catch (e) { setError(h.reason(e.reason) || s.reason(e.reason)); }
    finally { setBusy(false); }
  };
  const field = (name, label, type = 'text', required = true) => <label className="ld-field">{label}<input required={required} type={type} value={values[name] || ''} onChange={e => setValues(v => ({ ...v, [name]: e.target.value }))} /></label>;
  const select = (name, label, choices, required = true) => <label className="ld-field">{label}<select required={required} value={values[name] || ''} onChange={e => setValues(v => ({ ...v, [name]: e.target.value }))}><option value="">—</option>{choices.map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label>;
  const pickPropertyPhotos = async e => {
    const files = [...(e.target.files || [])].slice(0, 10 - propertyPhotos.length); e.target.value = '';
    for (const file of files) {
      const problem = photoProblem(file); if (problem) { setError(h.reason(problem)); continue; }
      try { const uploaded = await uploadProductPhoto(hasib, file); setPropertyPhotos(rows => [...rows, { id: uploaded.photoId, preview: URL.createObjectURL(uploaded.preview) }].slice(0, 10)); }
      catch (err) { setError(h.reason(err.reason) || h.reason('photo_upload_failed')); }
    }
  };
  const submit = e => {
    e.preventDefault();
    const submission = buildRealEstateSubmission(form, values, {
      requestId: crypto.randomUUID(),
      now: Date.now(),
      propertyPhotos,
      opportunities: data.opportunities?.items,
    });
    if (submission) return run(submission.operation, submission.body);
  };
  if (state.loading && !state.data) return <p className="ld-state">{s.t('loading')}</p>;
  if (state.error && !state.data) return <p className="ld-state" role="alert">{h.reason(state.error.reason) || s.reason(state.error.reason)}</p>;
  const head = (title, action, label, icon = 'building-2') => <PageHeader title={title} description={tr('Verified listings, qualified enquiries and controlled approvals.', 'قوائم موثقة واستفسارات مؤهلة وموافقات مضبوطة.')} icon={icon} primary={action ? { label, onClick: () => setForm(action) } : undefined} />;
  const editProperty = row => {
    setValues({ propertyId: row.id, version: row.version, label: row.label, reference: row.reference || '', transactionType: row.transactionType || 'sale', propertyType: row.propertyType || '', area: row.area || '', location: row.location || '', price: (row.askingPriceMinor || 0) / 1000, pricePeriod: row.pricePeriod || '', bedrooms: row.bedrooms || '', bathrooms: row.bathrooms || '', sizeSqm: row.sizeSqm || '', description: row.description || '', assignedAccountId: row.assignedAccountId || '', availability: row.availability || 'available', authorityStatus: row.authorityStatus || 'pending', features: (row.features || []).join(', ') });
    setPropertyPhotos((row.photoIds || []).map((id, index) => ({ id, preview: row.photoUrls?.[index] || '' })));
    setForm('property');
  };
  return <div className="hb-real-estate">
    {error && <p className="ld-inline-error" role="alert">{error}</p>}
    {mode === 'today' && <>{head(tr('Today', 'اليوم'), null, null, 'clock')}<ActionCards label={tr('Quick actions', 'إجراءات سريعة')} actions={[{id:'property',label:tr('Add property','إضافة عقار'),icon:'home',onClick:()=>onGo?.('stock',{action:'property'})},{id:'opportunity',label:tr('Add opportunity','إضافة فرصة'),icon:'users',onClick:()=>onGo?.('orders',{action:'opportunity'})},{id:'viewing',label:tr('Schedule viewing','جدولة معاينة'),icon:'calendar',onClick:()=>onGo?.('orders',{action:'viewing'})},{id:'offer',label:tr('Draft offer','مسودة عرض'),icon:'receipt',onClick:()=>onGo?.('orders',{action:'offer'})},{id:'follow-up',label:tr('Draft follow-up','مسودة متابعة'),icon:'message-circle',onClick:()=>onGo?.('orders',{action:'follow-up'})}]} />
      <MetricCards label={tr("Today's operating status", 'حالة العمل اليوم')} items={Object.entries(data.summary?.counts || {}).map(([key,value], index)=>({id:key,value,label:tr(({ opportunities:'Open opportunities',unassigned:'Unassigned',slaBreaches:'SLA breaches',staleListings:'Stale listings',todayViewings:"Today’s viewings",tasks:'Open tasks' })[key]||key,({ opportunities:'الفرص المفتوحة',unassigned:'غير معيّن',slaBreaches:'تجاوزات الاستجابة',staleListings:'قوائم قديمة',todayViewings:'معاينات اليوم',tasks:'مهام مفتوحة' })[key]||key),icon:['users','users','clock','home','calendar','target'][index],tone:value ? (['slaBreaches','staleListings','tasks'].includes(key)?'coral':'blue'):'green'}))} />
      <section><h2>{tr('Deal pipeline', 'مسار الصفقات')}</h2><div className="hb-pipeline">{Object.entries(data.summary?.pipeline || {}).map(([stage,count])=><article key={stage}><strong>{count}</strong><span>{stage}</span></article>)}</div></section>
      {(data.tasks?.items || []).length ? (data.tasks?.items || []).map(task => <section className="hb-panel" key={task.id}><b>{task.kind}</b><p>{task.reason}</p></section>) : <EmptyState icon="check" title={tr('Nothing urgent', 'لا توجد مهام عاجلة')} description={tr('SLA breaches, stale listings and approval tasks will appear here.', 'ستظهر هنا تجاوزات الاستجابة والقوائم القديمة ومهام الموافقة.')} />}</>}
    {mode === 'properties' && <>{head(tr('Properties', 'العقارات'), 'property', tr('Add property', 'إضافة عقار'), 'home')}{(data.properties?.items || []).length ? <div className="hb-real-grid">{data.properties.items.map(row => <article className="hb-panel hb-property-card" key={row.id}>{row.photoUrls?.find(Boolean) ? <img src={row.photoUrls.find(Boolean)} alt={row.label} loading="lazy" className="hb-property-cover" /> : <div className="hb-property-cover"><Icon name="home" size={42} /><span>{tr('Add listing photos', 'أضف صور العقار')}</span></div>}<div className="hb-property-body"><div className="hb-status-line"><h2>{row.label}</h2><span className="ld-chip">{row.availability}</span></div><p>{row.reference || '—'} · {row.propertyType || '—'} · {row.area || row.location}</p><p><b><Money h={h} minor={row.askingPriceMinor} /></b>{row.pricePeriod && ` / ${row.pricePeriod}`} · {row.bedrooms ?? '—'} {tr('beds', 'غرف')}</p><p>{row.authorityStatus || tr('Authority not recorded', 'لم تُسجل صلاحية الإعلان')} · {row.verificationAt ? formatDateTime(row.verificationAt, s.lang, timezone) : tr('Not verified', 'غير موثق')}</p><button type="button" className="ld-button" onClick={()=>editProperty(row)}>{tr('Edit listing', 'تعديل الإعلان')}</button></div></article>)}</div> : <EmptyState icon="home" title={tr('No properties yet', 'لا توجد عقارات بعد')} description={tr('Add a verified listing with its price, availability and photos.', 'أضف إعلاناً موثقاً مع السعر والتوفر والصور.')} action={{label:tr('Add property','إضافة عقار'),onClick:()=>setForm('property')}} />}</>}
    {mode === 'deals' && <>{head(tr('Customers and deals', 'العملاء والصفقات'), 'opportunity', tr('Add opportunity', 'إضافة فرصة'), 'users')}<ActionCards label={tr('Deal actions','إجراءات الصفقات')} actions={[{id:'opportunity',label:tr('Add opportunity','إضافة فرصة'),icon:'users',onClick:()=>setForm('opportunity')},{id:'viewing',label:tr('Schedule viewing','جدولة معاينة'),icon:'calendar',onClick:()=>setForm('viewing')},{id:'offer',label:tr('Draft offer','مسودة عرض'),icon:'receipt',onClick:()=>setForm('offer')},{id:'draft',label:tr('Draft follow-up','مسودة متابعة'),icon:'message-circle',onClick:()=>setForm('draft')}]} /><div className="hb-pipeline">{Object.entries(data.summary?.pipeline || {}).map(([stage,count])=><article key={stage}><strong>{count}</strong><span>{stage}</span></article>)}</div><div className="hb-real-grid"><section><h2>{tr('Pipeline', 'مسار الصفقات')}</h2>{(data.opportunities?.items || []).length ? data.opportunities.items.map(row => <article className="hb-panel" key={row.id}><div className="hb-row"><b>{row.need}</b><span className="ld-chip">{row.stage}</span></div><p>{row.areas.join(', ')} · <Money h={h} minor={row.budgetMaxMinor} /></p><p>{row.nextAction || tr('No next action', 'لا يوجد إجراء تالٍ')}</p><button className="ld-button" onClick={() => run('match_generate', { opportunityId: row.id })}>{tr('Refresh matches', 'تحديث المطابقات')}</button>{manager && <button className="ld-button" onClick={() => run('compliance_update', { opportunityId: row.id, workflow: { identityStatus:'confirmed', authorityStatus:'confirmed', financingStatus:'confirmed', agreementStatus:'confirmed', completionStatus:'confirmed' } })}>{tr('Confirm compliance checkpoints', 'تأكيد نقاط الامتثال')}</button>}</article>) : <EmptyState icon="users" title={tr('No opportunities yet','لا توجد فرص بعد')} description={tr('Add a qualified customer need to begin matching properties.','أضف احتياج عميل مؤهل لبدء مطابقة العقارات.')} action={{label:tr('Add opportunity','إضافة فرصة'),onClick:()=>setForm('opportunity')}} />}</section>
      <section><h2>{tr('Viewings', 'المعاينات')}</h2>{(data.viewings?.items || []).length ? data.viewings.items.map(row => <article className="hb-panel" key={row.id}><b>{formatDateTime(row.scheduledAt, s.lang, timezone)}</b><p>{row.status} · {row.outcome || tr('Outcome pending', 'النتيجة معلقة')}</p></article>) : <EmptyState icon="calendar" title={tr('No viewings yet','لا توجد معاينات بعد')} action={{label:tr('Schedule viewing','جدولة معاينة'),onClick:()=>setForm('viewing')}} />}</section>
      <section><h2>{tr('Offers and approvals', 'العروض والموافقات')}</h2>{(data.offers?.items || []).length ? data.offers.items.map(row => <article className="hb-panel" key={row.id}><b><Money h={h} minor={row.amountMinor} /></b><p>{row.status} · {row.terms}</p>{manager && row.status === 'draft' && <button className="ld-button" onClick={() => run('offer_approve', { offerId: row.id, version: row.version })}>{tr('Approve offer', 'الموافقة على العرض')}</button>}{['approved','presented','countered'].includes(row.status) && <button className="ld-button" onClick={() => run('offer_save', { offerId: row.id, version: row.version, workflow: { status: 'accepted' } })}>{tr('Record acceptance', 'تسجيل القبول')}</button>}{manager && row.status === 'accepted' && <button className="ld-button" onClick={() => { setValues({ opportunityId: row.opportunityId, offerId: row.id }); setForm('close'); }}>{tr('Close deal', 'إغلاق الصفقة')}</button>}</article>) : <EmptyState icon="receipt" title={tr('No offers yet','لا توجد عروض بعد')} action={{label:tr('Draft offer','مسودة عرض'),onClick:()=>setForm('offer')}} />}<h2>{tr('Outbound approvals', 'موافقات الإرسال')}</h2>{(data.drafts?.items || []).length ? data.drafts.items.map(row => <article className="hb-panel" key={row.id}><b>{row.kind}</b><p>{row.text}</p><span className="ld-chip">{row.status}</span>{manager && row.status === 'draft' && <button className="ld-button" onClick={() => run('draft_approve', { draftId: row.id, version: row.version })}>{tr('Approve and queue', 'الموافقة والإرسال للطابور')}</button>}</article>) : <p className="ld-help">{tr('No outbound drafts are waiting.','لا توجد مسودات إرسال معلقة.')}</p>}</section></div></>}
    {mode === 'money' && <>{head(tr('Money and insights', 'الأموال والمؤشرات'), null, null, 'bar-chart')}<MetricCards label={tr('Money and conversion measures', 'مؤشرات الأموال والتحويل')} items={[
      {id:'due',value:<Money h={h} minor={data.insights?.commissions?.dueMinor || 0}/>,label:tr('Commission due','العمولة المستحقة'),icon:'receipt',tone:'yellow'},
      {id:'paid',value:<Money h={h} minor={data.insights?.commissions?.paidMinor || 0}/>,label:tr('Commission paid','العمولة المدفوعة'),icon:'check',tone:'green'},
      {id:'response',value:data.insights?.averageFirstResponseMinutes ?? '—',label:tr('Avg. first response (min)','متوسط الرد الأول (دقيقة)'),icon:'clock'},
      {id:'qualified',value:`${data.insights?.qualificationRate || 0}%`,label:tr('Qualification rate','نسبة التأهيل'),icon:'target'},
      {id:'viewing',value:`${data.insights?.viewingToOfferRate || 0}%`,label:tr('Viewing to offer','من المعاينة إلى العرض'),icon:'calendar'},
      {id:'close',value:`${data.insights?.offerToCloseRate || 0}%`,label:tr('Offer to close','من العرض إلى الإغلاق'),icon:'trending-up'}]} /><div className="hb-metrics" hidden>
      <article className="hb-metric"><strong><Money h={h} minor={data.insights?.commissions?.dueMinor || 0} /></strong><span>{tr('Commission due', 'العمولة المستحقة')}</span></article>
      <article className="hb-metric"><strong><Money h={h} minor={data.insights?.commissions?.paidMinor || 0} /></strong><span>{tr('Commission paid', 'العمولة المدفوعة')}</span></article>
      <article className="hb-metric"><strong>{data.insights?.averageFirstResponseMinutes ?? '—'}</strong><span>{tr('Avg. first response (min)', 'متوسط الرد الأول (دقيقة)')}</span></article>
      <article className="hb-metric"><strong>{data.insights?.qualificationRate || 0}%</strong><span>{tr('Qualification rate', 'نسبة التأهيل')}</span></article>
      <article className="hb-metric"><strong>{data.insights?.viewingToOfferRate || 0}%</strong><span>{tr('Viewing to offer', 'من المعاينة إلى العرض')}</span></article>
      <article className="hb-metric"><strong>{data.insights?.offerToCloseRate || 0}%</strong><span>{tr('Offer to close', 'من العرض إلى الإغلاق')}</span></article>
      <article className="hb-metric"><strong>{data.insights?.averageDaysOnMarket ?? '—'}</strong><span>{tr('Avg. days on market', 'متوسط أيام العرض')}</span></article>
    </div>{(data.insights?.sourceConversion?.length || data.insights?.lostReasons?.length) ? <div className="hb-real-grid"><HorizontalBars title={tr('Source conversion', 'التحويل حسب المصدر')} rows={(data.insights?.sourceConversion || []).map(row=>({id:row.source,label:row.source,value:row.rate,detail:row}))} format={(value,row)=>`${row.detail.won}/${row.detail.opportunities} · ${value}%`} /><HorizontalBars title={tr('Lost reasons', 'أسباب الخسارة')} rows={(data.insights?.lostReasons || []).map(row=>({id:row.label,label:row.label,value:row.count}))} /></div> : <EmptyState icon="bar-chart" title={tr('No conversion history yet','لا يوجد سجل تحويل بعد')} description={tr('Charts will use recorded opportunities, offers and closes—never sample data.','ستستخدم الرسوم الفرص والعروض والإغلاقات المسجلة فقط، دون بيانات تجريبية.')} />}{(data.commissions?.items || []).length ? data.commissions.items.map(row => <section className="hb-panel" key={row.id}><b><Money h={h} minor={row.amountMinor} /></b><p>{row.status}</p>{row.status === 'due' && <button className="ld-button" onClick={() => run('commission_record', { commissionId: row.id, status: 'paid' })}>{tr('Mark paid', 'تسجيل كمدفوع')}</button>}</section>) : <EmptyState icon="receipt" title={tr('No commission records yet','لا توجد سجلات عمولة بعد')} description={tr('Agency commission appears here only after an approved compliant close.','تظهر عمولة الوكالة هنا فقط بعد إغلاق معتمد ومستوفٍ للامتثال.')} />}</>}
    {mode === 'team' && <>{head(tr('Team', 'الفريق'), 'invite', tr('Invite employee', 'دعوة موظف'), 'users')}<p className="ld-help">{tr(`One manager and up to ${data.team?.limit || 5} employees.`, `مدير واحد وحتى ${data.team?.limit || 5} موظفين.`)}</p>{(data.team?.members || []).length ? data.team.members.map(row => <section className="hb-panel hb-row" key={row.id}><div><b>{row.email}</b><p>{row.status}</p></div>{row.status === 'pending' && <button className="ld-button" onClick={() => run('team_resend', { memberId: row.id })}>{tr('Resend', 'إعادة الإرسال')}</button>}{row.status !== 'revoked' && <button className="ld-button ld-danger" onClick={() => run('team_revoke', { memberId: row.id })}>{tr('Revoke', 'إلغاء')}</button>}</section>) : <EmptyState icon="users" title={tr('No employees yet','لا يوجد موظفون بعد')} description={tr('Invite up to five employees. Manager-only controls remain protected.','ادعُ حتى خمسة موظفين، مع بقاء أدوات المدير محمية.')} action={{label:tr('Invite employee','دعوة موظف'),onClick:()=>setForm('invite')}} />}</>}
    {form && <form className="hb-panel hb-action-fields" onSubmit={submit}><h2>{tr('Record details', 'تسجيل التفاصيل')}</h2>
      {form === 'invite' && field('email', tr('Employee email', 'بريد الموظف'), 'email')}
      {form === 'property' && <>{field('label', tr('Listing title', 'عنوان الإعلان'))}{field('reference', tr('Listing reference', 'مرجع الإعلان'))}{select('transactionType', tr('Sale or rent', 'بيع أو إيجار'), [{id:'sale',label:tr('Sale','بيع')},{id:'rent',label:tr('Rent','إيجار')}])}{field('propertyType', tr('Property type', 'نوع العقار'))}{field('area', tr('Area', 'المنطقة'))}{field('location', tr('Location', 'الموقع'))}{field('price', tr('Price (OMR)', 'السعر (ر.ع.)'), 'number')}{field('pricePeriod', tr('Price period', 'مدة السعر'), 'text', false)}{field('bedrooms', tr('Bedrooms', 'غرف النوم'), 'number', false)}{field('bathrooms', tr('Bathrooms', 'الحمامات'), 'number', false)}{field('sizeSqm', tr('Size (m²)', 'المساحة (م²)'), 'number', false)}{field('description', tr('Description', 'الوصف'), 'text', false)}{select('availability', tr('Availability', 'التوفر'), ['available','reserved','unavailable'].map(id=>({id,label:id})))}{select('assignedAccountId', tr('Responsible employee', 'الموظف المسؤول'), manager ? (data.team?.members || []).filter(x => x.status === 'active' && x.accountId).map(x => ({id:x.accountId,label:x.email})) : [{id:overview.teamSummary?.actorAccountId,label:tr('Me','أنا')}], false)}{select('authorityStatus', tr('Authority to list', 'صلاحية الإعلان'), [{id:'confirmed',label:tr('Confirmed','مؤكد')},{id:'pending',label:tr('Pending','معلق')}])}{field('features', tr('Features, comma separated', 'المزايا، مفصولة بفواصل'), 'text', false)}<label className="ld-field">{tr('Listing photos (up to 10)', 'صور الإعلان (حتى ١٠)')}<input type="file" accept={PHOTO_TYPES.join(',')} multiple disabled={propertyPhotos.length >= 10} onChange={pickPropertyPhotos} /></label><div className="hb-property-photos">{propertyPhotos.map((photo, index) => <div key={photo.id}>{photo.preview ? <img src={photo.preview} alt={`${tr('Listing photo', 'صورة العقار')} ${index + 1}`} /> : <span>{tr('Saved photo','صورة محفوظة')} {index + 1}</span>}<button type="button" className="ld-button ld-danger" onClick={() => { if (photo.preview.startsWith('blob:')) URL.revokeObjectURL(photo.preview); setPropertyPhotos(rows => rows.filter(row => row.id !== photo.id)); }}>{tr('Remove', 'حذف')}</button></div>)}</div></>}
      {form === 'opportunity' && <>{select('contactId', tr('Customer', 'العميل'), (data.contacts?.items || []).map(x => ({id:x.id,label:x.name})))}{select('need', tr('Need', 'الاحتياج'), ['buy','rent','sell','invest'].map(id => ({id,label:id})))}{field('areas', tr('Preferred areas', 'المناطق المفضلة'))}{field('propertyTypes', tr('Property types', 'أنواع العقار'))}{field('budgetMin', tr('Minimum budget (OMR)', 'الحد الأدنى للميزانية'), 'number', false)}{field('budgetMax', tr('Maximum budget (OMR)', 'الحد الأعلى للميزانية'), 'number')}{field('bedrooms', tr('Bedrooms', 'غرف النوم'), 'number', false)}{select('financeReadiness', tr('Finance readiness', 'جاهزية التمويل'), ['ready','in_progress','cash','unknown'].map(id => ({id,label:id})))}{select('decisionMakerReadiness', tr('Decision maker', 'صاحب القرار'), ['ready','consulting','unknown'].map(id => ({id,label:id})))}{field('timeline', tr('Timeline', 'الإطار الزمني'))}{field('mustHaves', tr('Must-haves', 'المتطلبات الأساسية'), 'text', false)}{field('nextAction', tr('Next action', 'الإجراء التالي'), 'text', false)}</>}
      {form === 'opportunity' && <>{select('assignedAccountId', tr('Assigned employee', 'الموظف المسؤول'), manager ? (data.team?.members || []).filter(x => x.status === 'active' && x.accountId).map(x => ({id:x.accountId,label:x.email})) : [{id:overview.teamSummary?.actorAccountId,label:tr('Me','أنا')}], false)}</>}
      {form === 'viewing' && <>{select('opportunityId', tr('Opportunity', 'الفرصة'), (data.opportunities?.items || []).map(x => ({id:x.id,label:`${x.need} · ${x.areas.join(', ')}`})))}{select('propertyId', tr('Property', 'العقار'), (data.properties?.items || []).map(x => ({id:x.id,label:x.label})))}{field('scheduledAt', tr('Date and time', 'التاريخ والوقت'), 'datetime-local')}{field('nextAction', tr('Next action', 'الإجراء التالي'), 'text', false)}</>}
      {form === 'offer' && <>{select('opportunityId', tr('Opportunity', 'الفرصة'), (data.opportunities?.items || []).map(x => ({id:x.id,label:`${x.need} · ${x.areas.join(', ')}`})))}{select('propertyId', tr('Property', 'العقار'), (data.properties?.items || []).map(x => ({id:x.id,label:x.label})))}{field('amount', tr('Offer amount (OMR)', 'قيمة العرض (ر.ع.)'), 'number')}{field('terms', tr('Bounded terms', 'شروط العرض'))}</>}
      {form === 'draft' && <>{select('opportunityId', tr('Opportunity', 'الفرصة'), (data.opportunities?.items || []).map(x => ({id:x.id,label:`${x.need} · ${x.areas.join(', ')}`})))}{select('kind', tr('Message type', 'نوع الرسالة'), ['follow_up','viewing_confirmation','offer'].map(id => ({id,label:id})))}{field('text', tr('Draft text', 'نص المسودة'))}{field('templateId', tr('Approved utility template ID (outside 24h)', 'معرّف قالب الخدمة المعتمد (خارج 24 ساعة)'), 'text', false)}</>}
      {form === 'close' && <>{field('commission', tr('Agency commission only (OMR)', 'عمولة الوكالة فقط (ر.ع.)'), 'number')}</>}
      <div className="ld-actions"><button className="ld-button ld-primary" disabled={busy}>{busy ? h.t('saving') : h.t('save')}</button><button type="button" className="ld-button" onClick={() => { for (const photo of propertyPhotos) URL.revokeObjectURL(photo.preview); setPropertyPhotos([]); setForm(''); }}>{s.t('cancel')}</button></div></form>}
  </div>;
}
